
import { GoogleGenAI } from '@google/genai';
import type { GeneratorFormState } from '../types';

if (!process.env.API_KEY) {
  // This is a placeholder check. The actual key is expected to be in the environment.
  console.warn("API_KEY environment variable not set. API calls will fail.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY! });

const generatePrompt = (formState: GeneratorFormState): string => {
  const { gameDescription, characterDescription, imageStyle, pixelSize } = formState;

  if (imageStyle === 'pixel') {
    return `A ${pixelSize}x${pixelSize} pixel art sprite of a game character. The character is for a game with the following theme: "${gameDescription}". Character details: "${characterDescription}". The style should be classic 16-bit RPG sprite art, clean and readable. The background must be transparent. Only one character per image.`;
  } else {
    return `A full-body character portrait in a Japanese anime/manga "Tachie" style. The character is for a game with the following theme: "${gameDescription}". Character details: "${characterDescription}". The background must be transparent. High resolution, clean lines, and vibrant colors.`;
  }
};

export const generateCharacterImages = async (formState: GeneratorFormState): Promise<string[]> => {
  const prompt = generatePrompt(formState);
  const aspectRatio = formState.imageStyle === 'pixel' ? '1:1' : '9:16';
  
  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: formState.numImages,
        outputMimeType: 'image/png',
        aspectRatio: aspectRatio,
      },
    });

    if (!response.generatedImages || response.generatedImages.length === 0) {
      throw new Error('No images were generated by the API.');
    }
    
    return response.generatedImages.map(img => `data:image/png;base64,${img.image.imageBytes}`);
  } catch (error) {
    console.error('Error calling Gemini API:', error);
    throw new Error('Failed to communicate with the image generation service.');
  }
};
   